language: node_js
node_js:
- '4.2.2'
before_script:
- npm install -g bower
- bower install
script:
- grunt
env:
  global:
  - secure: lIdv8bI/nIWcvsgEKoTuvCU3oofya2/pCSHB6kV6/ipu33TJ8s88VkRq+wZ5XXvWC8crM+M+wL4B+OQ+JhhToAdWIo1ut4B/SLLCaa91iHMPcBa63V7jv4TaX5MlDyLMT+CWSPB7TY+oPp+Dw4EIdm5e17YrpbdHKJ61qscVzCs=
  - secure: PDOY9C8nY5tfWG5eW5wh5NzYzquoWO/ldJno5Z/RaNVnWLfJMlDegqXSt58WDZ4MG/apW/BUzFOmxjpc1ATfxhg32v2bF5nGWTxkArZI2g6fHKk2k9UxqC/qwk0X/hOLvIhrZtktkSw+APRIfwwybF/RnzqjJMrN8WpgQ6ibMJ4=
