language: node_js
node_js:
- 4.2.2
before_script:
- npm install -g bower
- bower install
script:
- grunt
env:
  global:
  - secure: SLzf8W4vTcvnsGYD6Pj/rkhhrX7KLwwP6ozZJG0gzcl2YIynlrmxHDuvqBUF/Q489Mu4/HMWjGRZAnjY4ISOgUMjNmrsvLTdpr9Fb48vhJrEhXY8mFLfPvkKn5exMD9zMO58SnDxkxkNMYH2cUCRNXs+VOg62TzNruZZq85IvAA=
  - secure: O+PGDpAtcWNQE+B3P4+0euM8xHmPc9zG8dP4KDUaR4jE/FJgyHprEVfW8+836+hLwBlggXxPG+fJcJq2/nz8LwL4ojyHks0k5/OMJ13ocFsDU7kZ0oJs13s0Sb97Z8mC1qaOYqcZNw4BHyhaHxo4ZGqRZx+41YL407GwIf5EDG4=
