language: node_js
node_js:
- 4.2.2
before_script:
- npm install -g bower
- bower install
script:
- grunt
env:
  global:
  - secure: OmW4JssXPZE9fpT0H9bnO+F1Q3a7HwdpVav2qagLnK6g/MU7HbMlEZBTk5X32KlvRryTuQEQP5LcHPM5gDmP0jYmRnthr0NOgxPVQt85ifj9VIBMLJgj67T06Cdth7rKdASLLqK+3FnmkC9+HIFVN/tf2YWaEL6SUbhChRWO23M=
  - secure: oc/cd01UyH4WesDea7E1H+bZMahcEuXC5S/zOw/ouhWSpFzRLVxHyC7qZL4JmsSHt5UBolySllqTXcARFKYiWqGhJAKKoS/MgZytnhThiKckCyWgdHAMRW8WJW3z7t9KZTnNsLwkqYe4U4xnKATqzPlpp9h5N8HTJWbuoYYVNLw=
