sudo: false
language: node_js
node_js:
- 4.2.2
before_script:
- npm install -g bower
- bower install
script:
- grunt
env:
  global:
  - secure: qBzuNAnRaqs368Bhlj+Nnd75G/FdadRsOJjjRRVrsYYbBTzLYDHjQ/oyZG/ikGUlFMPP+osfeOIcB91xi6u+uv7Ig3/d3GsInX9oqaQNqRODCwQXUKVP+yC9MV8I8Wz/tmr08EdeGK83wBR7c3BwLVBmMNZx2Prl2xkTx2l329I=
  - secure: St0/ds4NwCr9/G6tDM4riMsadc3Es9HzojTxhHZpLvxDAxEerBgMYdTiTDsF8n92EERWEDMHbIZziUoWShPJ5FqTUvHdRFIdVA2wqRN4rVNZp52KTUe37u7ABwKEsSUA7e6aMtQDkyQXwgC7+tynb3CtyVXuVa7CsC3CMXfWY4M=
